# Generated by Django 4.0.3 on 2022-03-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(db_column='Branch_Name', max_length=50)),
                ('course_id', models.IntegerField(db_column='Course_id')),
            ],
            options={
                'db_table': 'Branch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_column='city_Name', max_length=50)),
                ('state_id', models.IntegerField(db_column='State_id')),
            ],
            options={
                'db_table': 'City',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(db_column='Course_Name', max_length=50)),
                ('course_type', models.CharField(db_column='Course_type', max_length=30)),
            ],
            options={
                'db_table': 'Course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(db_column='Institute_Name', max_length=70)),
                ('city_id', models.IntegerField(db_column='City_id')),
                ('state_id', models.IntegerField(db_column='State_id')),
                ('university_id', models.IntegerField(db_column='University_id')),
            ],
            options={
                'db_table': 'Institute',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles_name', models.CharField(db_column='Roles_Name', max_length=50)),
            ],
            options={
                'db_table': 'Roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(db_column='State_Name', max_length=50)),
            ],
            options={
                'db_table': 'State',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(db_column='Location_Name', max_length=50)),
                ('city_id', models.IntegerField(db_column='City_id')),
                ('state_id', models.IntegerField(db_column='State_id')),
            ],
            options={
                'db_table': 'Sub_Location',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(db_column='University_Name', max_length=70)),
                ('state_id', models.IntegerField(db_column='State_id')),
            ],
            options={
                'db_table': 'University',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAddressDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_for_communication', models.CharField(db_column='Address_for_communication', max_length=300)),
                ('pin_code', models.IntegerField(db_column='Pin_code')),
                ('current_residing_city', models.IntegerField(db_column='Current_Residing_city')),
                ('sub_location', models.IntegerField(db_column='Sub_Location')),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'User_Address_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First_Name', max_length=50)),
                ('last_name', models.CharField(db_column='Last_Name', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=40, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=40)),
                ('date_of_birth', models.DateField(db_column='Date_Of_Birth')),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=6, null=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'User_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserHighestQualificationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.IntegerField(db_column='Highest_Qualification')),
                ('branch', models.IntegerField(db_column='Branch')),
                ('passout_month', models.IntegerField(db_column='Passout_month')),
                ('passout_year', models.IntegerField(db_column='Passout_year')),
                ('marks_type', models.CharField(blank=True, db_column='Marks_type', max_length=10, null=True)),
                ('marks', models.FloatField(db_column='Marks')),
                ('state', models.IntegerField(db_column='State')),
                ('institute', models.IntegerField(db_column='Institute')),
                ('university', models.IntegerField(db_column='University')),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'User_Highest_Qualification_Details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.IntegerField(db_column='Roles')),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'User_Roles',
                'managed': False,
            },
        ),
    ]
